### ISSUE TITLE
API 1.0 no longer supported in maas 2.0

### ISSUE THREAD

**Issue by tpmullan** [chef-partners/knife-maas#21]
I would like to use this project, but it is using a deprecated API and does not work with the current version of maas.  Is there currently any plan to implement the new API?

When I run knife maas server list:
`ERROR: JSON::ParserError: 784: unexpected token at 'The 1.0 API is no longer available. Please use API version 2.0.'`

**Comment by jjasghar** [comment]
The rewrite is in my backlog, but it's unlikely it'll be done in the near future.
